### ISSUE TITLE
Improve milestones visualization

### ISSUE THREAD

**Issue by microstudi** [Platoniq/decidim-module-time_tracker#21]
At the bottom of the time tracker component, there is a list of participants with the last milestone displayed.
![image](https://user-images.githubusercontent.com/1401520/95215874-c5ae9d80-07f1-11eb-8f20-52d8d75d185b.png)

- [x] Image should be clickable

The public display of milestones looks like this:
![image](https://user-images.githubusercontent.com/1401520/95215997-e4149900-07f1-11eb-86b6-4be4f186d83c.png)

- [x] It should show the milestones per activity
- [x] It should be a way to show the images bigger. A possibility is to use a slideshow for every activity
```
Some activity
-slide show of milestones for this activity for the user-
Another activity
-slide show of milestones for this activity for the user-
```
- [x] Add milestones_controller tests
