### ISSUE TITLE
Questionnaires fixes & improvements

### ISSUE THREAD

**Issue by microstudi** [Platoniq/decidim-module-time_tracker#28]
Related to PR #26 

Admin:

- [x] Add migrations to add questionnaire to existing Activities, Tasks
- [x] Change admin icon for questionnaire
- [x] Remove custom questionnaires from activities, lets focus on Task questionnaires only. This will facilitate the creation of graphs where to compare different activities
- [ ] Give the admin a way to go back when editing questionnaire
- [x] Allow users to answer the same questionnaire if activities are different
- [x] Return to task list after saving questionnaire
- [ ] Pre-populate a template with a simple questionnaire - superseed by #38
    - 2 questions: what reputation has this task (from 1 to 10)? what is your perception about this task, who does this task usually: women, man, equal, N/A
- [ ] Pre-populate terms and services? - superseed by #38
- [ ] Add questionnaire seeds - superseed by #38

Front:

- [x] When a task has a questionnaire, it should appear a button to answer it (see doubts)
- [x] Use another endpoint than `join` to answer the questionnaire
- [x] Check the behavior (and fix) when user is answering the questionnaire

Doubts:

- Should we make mandatory to answer a questionnaire when joining an activity?

**Comment by microstudi** [comment]
I think we should make the questionnaire answering optional, and show a button to the user with the questionnaire access if not responded yet, either in the context of a task or an activity
